services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inversiones_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - inversiones_network

networks:
  inversiones_network:
    driver: bridge